# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Server-HTTPServer
version:      0.9.2
version_from: lib/POE/Component/Server/HTTPServer.pm
installdirs:  site
requires:
    HTTP::Message:                 1.3
    HTTP::Status:                  0
    MIME::Types:                   1.06
    POE:                           0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
